inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstParameterIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: true
  IgnoredMethods:
    - require
    - require_relative
    - require_dependency
    - yield
    - raise
    - puts
    - to
    - not_to
    - to_not
    - describe
  Exclude:
    - "**/Gemfile"
    - "db/**/*"
